name: Windows-exe-build

on:
  workflow_dispatch:

jobs:
  build-windows:
    name: 🪟 Windows Build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.44.6'

      - run: flutter pub get

      - run: flutter build windows --release

      - name: Zip output
        run: Compress-Archive -Path build/windows/x64/runner/Release/* -DestinationPath genz-windows.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: genz-windows
          path: genz-windows.zip
